### ISSUE TITLE
Delete or modify problematic `virtualenv>=16.6.0` for Travis

### ISSUE THREAD

**Issue by nealmcb** [ionelmc/cookiecutter-pylibrary#181]
I just put up a new repository based on cookiecutter-pylibrary. It helped us quickly make progress with integrations - thanks!

But we ran into a problem with our first travis build (see [details](https://travis-ci.org/gwexploratoryaudits/r2b2/jobs/649180263)), which failed while documenting the environment.

```
$ virtualenv --version
Traceback (most recent call last):
...
ImportError: cannot import name 'ensure_text' from 'six' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/six.py)
```
`ci/requirements.txt` lists this: `virtualenv>=16.6.0`
and a new version is out recently: 20.0.2.

It seems that virtualenv 16.1.0 was already installed, which is incompatible with six 1.11.0 which we got elsewhere.

```
 Found existing installation: virtualenv 16.1.0
  Uninstalling virtualenv-16.1.0:
 virtualenv 20.0.2 has requirement six<2,>=1.12.0, but you'll have six 1.11.0 which is incompatible.
```

The travis build seems to have worked after I simply removed the version requirement on `virtualenv>=16.6.0`.
What is it that required that a later version?

**Comment by ionelmc** [comment]
16.6.0 is listed as a minimum because other stuff would be broken without it. The solution, and workaround to pip's lousy dep resolver is to also have a min requirement for six. I suspect it doesn't upgrade it cause it's already installed and `--upgrade` wasn't used. But we can't use `--upgrade` cause that would upgrade everything (slow and dangerous).

16.6.0 bundles pip 19.1.1 which in turn fixes broken develop installs when there's a pyproject.toml (eg: setuptools-scm is enabled).
