### ISSUE TITLE
Make use of tox dimensionality

### ISSUE THREAD

**Issue by cmeeren** [ionelmc/cookiecutter-pylibrary#33]
See https://testrun.org/tox/latest/config-v2.html

It says on the top that it's a draft, but then it says later on that 1.4 is the "current configuration", and my installed tox at least is version 2.0. So if the features described on that page have been implemented, then it might be worth it to make use of them. (I have no idea what kind of changes this would entail for this project).

**Comment by ionelmc** [comment]
It's already supported if you set "test_matrix_configurator" to "no" when you make the project. But then you have to manually edit `appveyor.yml` and `.travis.yml` (could be fixed with some tool however).

Eg: https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L17-L41

**Comment by cmeeren** [comment]
I see. Personally I'd rather keep the auto-generation of those two files, so I'll stick to the test matrix configurator. :)
