### ISSUE TITLE
Purpose of WITH_COVERAGE

### ISSUE THREAD

**Issue by vmuriart** [ionelmc/cookiecutter-pylibrary#73]
Thanks for putting together such a robust template! Big fan of it

I couldn't find any references as to what that env var purpose is. The closest I found was [NOSE](http://nose.readthedocs.io/en/latest/plugins/cover.html#cmdoption--with-coverage) using a similar variable. 

Whats the benefit of running the tests with and without coverage? On all my projects I always run them with coverage on.

Thanks again,

**Comment by vmuriart** [comment]
On my second question, I'm starting to suspect that I may not be seeing the benefit because of how the projects I have coverage on are [laid out](https://blog.ionelmc.ro/2014/05/25/python-packaging/).

**Comment by ionelmc** [comment]
This env duplication is usually necessary in timing sensitive projects (as I have found out bugs in https://pypi.python.org/pypi/manhole or https://pypi.python.org/pypi/pytest-benchmark I wouldn't been able to find otherwise).

It's a good practice for complicated projects but as you can see the default options (`test_matrix_separate_coverage=no`) of this template make a project without the `cover/nocov` envs - it makes everything twice as slow 😁

**Comment by vmuriart** [comment]
Awesome! thanks for the info. 

I just realized my first question talks about a missing reference, but i never said what I was talking about. I had meant the WITH_COVERAGE env. variable.

**Comment by ionelmc** [comment]
I forgot about it. Some support env var for subprocess setup for coverage that I used long time ago. No longer necessary now (pytest-cov already does it).

**Comment by vmuriart** [comment]
Awesome. Thanks!
